# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: caerurfapugsAPI

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1
  profile: serverless-admin
  iamRoleStatements:
    -  Effect: "Allow"
       Action:
         - "ses:SendEmail"
       Resource:
         - "*"

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:
  mailinglist:
    handler: handler.mailinglist
    environment: ${file(./env.yml):${opt:stage, self:provider.stage}}
    events:
      - http:
          path: mailinglist
          method: post
  enquiry:
    handler: handler.enquiry
    environment: ${file(./env.yml):${opt:stage, self:provider.stage}}
    events:
      - http:
          path: enquiry
          method: post

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
